# Generated by Django 4.2.6 on 2024-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpeekbackendapp', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://avatars.githubusercontent.com/u/145338610?v=4', max_length=100),
            preserve_default=False,
        ),
    ]
