# Generated by Django 4.2.6 on 2024-01-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airpeekbackendapp', '0003_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flights',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='userflights',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
